### PR TITLE
feat: [PIPE-20464]: add demo for signup and signin pages

### PR DESCRIPTION
**Pull request by cjlee01**
Summary:
add static pages for signup and signin pages based off mockups
https://www.figma.com/design/Q8CJSyrX6sZ6otjf8xhwSk/UI-Milestone-1?node-id=1-1038&t=q3fV2pqT8f7DxxkS-0

https://github.com/user-attachments/assets/54512b0c-8782-4349-82df-14ee9cc839d1

### CODE REVIEW

**Comment by joetaylor-harness** [comment]
Hey, I just started working with @bradrydzewski today on the unified ui work, so I'm not yet fully up-to-speed but nice work @cjlee01 with kicking things off. 

The figma url in the summary doesn't work for me, but the demo video looks like https://www.figma.com/design/Lu5QJyq9tQEjHMeQmQhbAd/Gitness-Product-Design---Stage-2?node-id=255-4341&t=lpeUzB6u7EAtZtem-4 is the basis here?

**Comment by cjlee01** [comment]
> Hey, I just started working with @bradrydzewski today on the unified ui work, so I'm not yet fully up-to-speed but nice work @cjlee01 with kicking things off.
> 
> The figma url in the summary doesn't work for me, but the demo video looks like https://www.figma.com/design/Lu5QJyq9tQEjHMeQmQhbAd/Gitness-Product-Design---Stage-2?node-id=134-315&t=lpeUzB6u7EAtZtem-4 is the basis here?

oh weird @joetaylor-harness, they look to be same to me ! Maybe ask @vardanbansal-harness  or @bradrydzewski  about it?

**Review by vardanbansal-harness — APPROVED** [review]

**Comment by joetaylor-harness** [comment]
Let's hold off merging, the component needed re-factoring to 
- work with Storybook, 
- handle validation,
- match the pixel point design. 

I've done most of this already, let's catch up on it later.

**Comment by joetaylor-harness** [comment]
@cjlee01 definitely close to the design but it isn't a match.

**Comment by cjlee1** [comment]
> @cjlee01 definitely close to the design but it isn't a match.

Sounds good to me, are you going to put a commit on this pr ? @joetaylor-harness

**Comment by joetaylor-harness** [comment]
@cjlee01 I've actually included the sign in / up components as part of the storybook push https://github.com/harness/canary/pull/12

**Comment by tan-nhu** [comment]
Closed this PR since we already moved Calvin's code into StoryBook

**Pull request closed without merging**
